### PR TITLE
feat: added hasheader param in z-modal

### PR DESCRIPTION
**Pull request by mikelina**
The hasheader property allow to create z-modal without header. 

It will be like this: 
Schermata 2020-08-11 alle 12 36 10

### CODE REVIEW

**Review by ufollettu — APPROVED** [review]

**Comment by edoardocavazza** [comment]
I'm not sure about moving the header inside the scrollable area, is this a design spec?

**Comment by vpasquino** [comment]
> I'm not sure about moving the header inside the scrollable area, is this a design spec?

Sometimes the modal needs to be headerless:

Schermata del 2020-09-15 12-46-00
Schermata del 2020-09-15 12-46-00

Abstract ref: https://app.abstract.com/projects/bb5cf030-8385-11e9-b424-6d122102c199/branches/7d66c032-ee64-42d4-beeb-cf9aa0db3ad5/collections/cdf46e42-7726-413d-a3ad-cb0a862b7f9b

**Comment by edoardocavazza** [comment]
> Sometimes the modal needs to be headerless

I got it, but why does the header need to be in the scrollable area when it exists?

**Comment by vpasquino** [comment]
> > Sometimes the modal needs to be headerless
> 
> I got it, but why does the header need to be in the scrollable area when it exists?

Where would you put it? The closing icon needs to overlap the content, this seemed like the best solution, do you have a better solution? :)

**Comment by edoardocavazza** [comment]
I am sorry, I thought that `scrollWrapper` was the element with scroll, but now I see it is not 😅

**Comment by vpasquino** [comment]
Oops, maybe the class name is not the best one, the whole modal scrolls. :sweat_smile:

**Pull request closed without merging**
