### PR TITLE
z-menu-dropdown component refactoring

### PR DESCRIPTION
**Pull request by vpasquino**
This PR solves this line-height problem:

Schermata del 2020-08-17 12-01-13

Schermata del 2020-08-17 12-03-23

This PR also fixes css (mobile first) and breakpoints.

### CODE REVIEW

**Comment by ufollettu** [comment]
I think this component needs refactoring due to the use of max-width @media query instead of min-width

**Comment by vpasquino** [comment]
> I think this component needs refactoring due to the use of max-width @media query instead of min-width and the lack of css variables use

Do you want to fix this in this PR? This is a simple line-height fix, but if you'd rather fix everything here, go ahead :)

**Review by ufollettu — APPROVED** [review]

**Comment by wanbinkimoon** [comment]
@vpasquino can you please update this PR and check is still working for merge?

----
@francescochiapella as reviewer

**Comment by vpasquino** [comment]
@wanbinkimoon still good for merging!

**Review by francescochiapella — APPROVED** [review]

**Pull request merged**
